name: Autofix new

on:
  issue_comment:
    types: [created]

jobs:
  laravel-pint:
    uses: ./.github/workflows/pint.yaml
    with:
      autofix: true
    secrets:
      lint_PAT: ${{ secrets.LINT_PAT }}
    if: >-
      contains(github.event.comment.body, '/autofix') &&
      github.event.issue.pull_request
