name: Autofix

on:
  issue_comment:
    types: [created]

jobs:
  laravel-pint:
    name: Laravel Pint
    if: contains(github.event.comment.body, '/autofix') && github.event.issue.pull_request
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"    

    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.LINT_PAT }}

    - name: Checkout Pull Request
      env:
        GH_TOKEN: ${{ secrets.LINT_PAT }}
      run: gh pr checkout "${{ github.event.issue.number }}"

    - name: Set $FILES
      run: |
        git remote -v
        git branch -v -a
        FILES=$(git diff --diff-filter=d --name-only origin/main | tr '\n' ' '|sed 's/,*$//g')
        echo $FILES
        echo "FILES=$FILES" >> "$GITHUB_ENV"

    - name: Install Pint
      run: composer global require --no-progress -- laravel/pint

    - name: Run Pint (Autofix)
      run: /home/runner/.composer/vendor/bin/pint -v ${{ env.FILES }}

    - name: Push changes
      env:
        GH_TOKEN: ${{ secrets.LINT_PAT }}
      run: |
        git config user.name "LibreNMS Bot"
        git config user.email "librenms-bot@users.noreply.github.com"
        git add .
        git commit -m "Apply Laravel Pint changes"
        git push
