name: Autofix

on:
  issue_comment:
    types: [created]

jobs:
  laravel-pint:
    name: Laravel Pint
    if: contains(github.event.comment.body, '/autofix') && github.event.issue.pull_request
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3

    - name: Checkout Pull Request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: hub pr checkout "${{ github.event.issue.number }}"

    - name: Set $FILES
      run: |
        git remote -v
        git branch -v -a
        FILES=$(git diff --diff-filter=d --name-only origin/main | tr '\n' ' '|sed 's/,*$//g')
        echo $FILES
        echo "FILES=$FILES" >> "$GITHUB_ENV"

    - name: Install Pint
      run: composer global require --no-progress -- laravel/pint

    - name: Run Pint (Autofix)
      run: /home/runner/.composer/vendor/bin/pint -v ${{ env.FILES }}

    - uses: stefanzweifel/git-auto-commit-action@v4
      if: contains(github.event.comment.body, '/autofix')
      with:
        commit_message: Apply Laravel Pint changes
