name: Autofix

on:
  issue_comment:
    types: [created]

jobs:
  laravel-pint:
    name: Laravel Pint
    if: contains(github.event.comment.body, '/autofix') && github.event.issue.pull_request
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"    
    
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.LINTER }}

    - name: Checkout Pull Request
      env:
        GITHUB_TOKEN: ${{ secrets.LINTER }}
        GH_TOKEN: ${{ secrets.LINTER }}
      run: hub pr checkout "${{ github.event.issue.number }}"

    - name: Set $FILES
      run: |
        git remote -v
        git branch -v -a
        FILES=$(git diff --diff-filter=d --name-only origin/main | tr '\n' ' '|sed 's/,*$//g')
        echo $FILES
        echo "FILES=$FILES" >> "$GITHUB_ENV"

    - name: Install Pint
      run: composer global require --no-progress -- laravel/pint

    - name: Run Pint (Autofix)
      run: /home/runner/.composer/vendor/bin/pint -v ${{ env.FILES }}


    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.LINTER }}
        GH_TOKEN: ${{ secrets.LINTER }}
      run: |
        gh auth login
        gh auth setup-git
        #git config user.name "Troll"
        #git config user.email "Troll@localhost"
        git add .
        git commit -m "Apply Laravel Pint changes"
        git push

#    - uses: stefanzweifel/git-auto-commit-action@v4
#      if: contains(github.event.comment.body, '/autofix')
#      with:
#        commit_message: Apply Laravel Pint changes
