name: Lint new

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  laravel-pint:
    uses: ./.github/workflows/pint.yaml

  laravel-pint2:
    uses: ./.github/workflows/pint.yaml
    with:
      autofix: true
    secrets:
      lint_pat: ${{ secrets.LINT_PAT }}
