name: Laravel Pint

on:
  workflow_call:
    inputs:
      autofix:
        default: false
        required: false
        type: boolean
    secrets:
      lint_PAT:
        required: false

jobs:
  laravel-pint:
    name: Laravel Pint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      #with:
      #  token: ${{ secrets.lint_PAT }}

    - name: Checkout Pull Request
      run: gh pr checkout ${{ github.event.issue.number }}
      env:
        GH_TOKEN: ${{ secrets.lint_PAT }}
      if: ${{ inputs.autofix }}

    - name: Set $FILES
      run: |
        FILES=$(git diff --diff-filter=d --name-only origin/main | tr '\n' ' ' | sed 's/,*$//g')
        echo $FILES
        echo "FILES=$FILES" >> "$GITHUB_ENV"
        echo test >> README.md

    - name: Install Pint
      run: composer global require --no-progress -- laravel/pint

    - name: Run Pint
      id: pint
      run: /home/runner/.composer/vendor/bin/pint -v --test ${{ env.FILES }}
      if: ${{ ! inputs.autofix }}

    - name: Create comment
      uses: peter-evans/create-or-update-comment@v4
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          Please comment `/autofix` to automatically fix the found problems.
      if: ${{ failure() && steps.pint.conclusion == 'failure' }}

#    - name: Run Pint (Autofix)
#      run: /home/runner/.composer/vendor/bin/pint -v ${{ env.FILES }}
#      if: ${{ inputs.autofix }}

    - name: Push changes (Autofix)
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Apply Laravel Pint changes
      if: ${{ inputs.autofix }}
