name: Laravel Pint

on:
  workflow_call:
    inputs:
      autofix:
        default: false
        required: false
        type: boolean
    secrets:
      lint_pat:
        required: false
jobs:
  laravel-pint:
    name: Laravel Pint
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set $FILES
      run: |
        FILES=$(git diff --diff-filter=d --name-only origin/main | tr '\n' ' ' | sed 's/,*$//g')
        echo $FILES
        echo "FILES=$FILES" >> "$GITHUB_ENV"

    - name: Install Pint
      run: composer global require --no-progress -- laravel/pint

    - name: Run Pint
      run: /home/runner/.composer/vendor/bin/pint -v --test ${{ env.FILES }}
      if: ${{ ! inputs.autofix }}

    - name: Run Pint (Autofix)
      run: /home/runner/.composer/vendor/bin/pint -v ${{ env.FILES }}
      if: ${{ inputs.autofix }}

    - name: Push changes (Autofix)
      env:
        GH_TOKEN: ${{ secrets.lint_path }}
      run: |
        git config user.name "LibreNMS Bot"
        git config user.email "librenms-bot@users.noreply.github.com"
        git add .
        git commit -m "Apply Laravel Pint changes"
        git push
      if: ${{ inputs.lint_path }}
