name: laravel-pint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  laravel-pint:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}

#    -
#      name: Set up PHP
#      uses: shivammathur/setup-php@v2
#      with:
#        php-version: ${{ matrix.php }}
#        tools: composer
#        coverage: none

    -
      name: Composer install
      run: composer global require --no-progress -- laravel/pint

    -
      name: Run Laravel Pint
      run: pint -v


#    - name: "laravel-pint"
#      uses: aglipanci/laravel-pint-action@2.2.0
#      with:
#        preset: laravel
#        verboseMode: true
#        onlyDirty: true

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply Laravel Pint changes
