name: Lint

on:
  pull_request:
  push:
    branches:
      - main
  issue_comment:
    types: [created]

jobs:
  laravel-pint:
    name: Laravel Pint
    if: |
      (github.event.issue.pull_request && contains(github.event.comment.body, '/autofix')) ||
      ! github.event.issue
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    - uses: actions/checkout@v3

    - name: Checkout Pull Request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ISSUE_NR="${{ github.event.issue.number }}"
        PR_NR="${{ github.event.number }}"

        if [ -z "$ISSUE_NR" ]
        then
          hub pr checkout $PR_NR
        else
          hub pr checkout $ISSUE_NR
        fi

    - name: Set $FILES
      run: |
        git remote -v
        git branch -v -a
        FILES=$(git diff --diff-filter=d --name-only origin/main | tr '\n' ' '|sed 's/,*$//g')
        echo $FILES

        echo 'FILES<<EOF' >> "$GITHUB_ENV"
        echo $FILES >> "$GITHUB_ENV"
        echo 'EOF' >> "$GITHUB_ENV"

        echo "FILES1=$FILES" >> "$GITHUB_ENV"

    - name: Composer install
      run: composer global require --no-progress -- laravel/pint

    - name: Run Laravel Pint
      if: ${{ !contains(github.event.comment.body, '/autofix') }}
      run: /home/runner/.composer/vendor/bin/pint -v --test ${{ env.FILES1 }}

    - name: Run Laravel Pint (Autofix)
      if: contains(github.event.comment.body, '/autofix')
      run: /home/runner/.composer/vendor/bin/pint -v ${{ env.FILES }}

    - uses: stefanzweifel/git-auto-commit-action@v4
      if: contains(github.event.comment.body, '/autofix')
      with:
        commit_message: Apply Laravel Pint changes
